name: Deploy to Surge & InfinityFree

on:
  push:
    branches:
      - main

jobs:
  surge-deploy:
    name: Deploy to Surge.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./ hangga-tools.surge.sh --token ${{ secrets.SURGE_TOKEN }}

  infinityfree-deploy:
    name: Deploy to InfinityFree via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
